// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ProposalRegistry$Type } from "./ProposalRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ProposalRegistry"]: ProposalRegistry$Type;
    ["contracts/ProposalRegistry.sol:ProposalRegistry"]: ProposalRegistry$Type;
  }

  interface ContractTypesMap {
    ["ProposalRegistry"]: GetContractReturnType<ProposalRegistry$Type["abi"]>;
    ["contracts/ProposalRegistry.sol:ProposalRegistry"]: GetContractReturnType<ProposalRegistry$Type["abi"]>;
  }
}
