// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IProposalRegistry$Type } from "./IProposalRegistry";
import { ReentrantMaliciousReceiver$Type } from "./ReentrantMaliciousReceiver";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IProposalRegistry"]: IProposalRegistry$Type;
    ["ReentrantMaliciousReceiver"]: ReentrantMaliciousReceiver$Type;
    ["contracts/test/ReentrantMaliciousReceiver.sol:IProposalRegistry"]: IProposalRegistry$Type;
    ["contracts/test/ReentrantMaliciousReceiver.sol:ReentrantMaliciousReceiver"]: ReentrantMaliciousReceiver$Type;
  }

  interface ContractTypesMap {
    ["IProposalRegistry"]: GetContractReturnType<IProposalRegistry$Type["abi"]>;
    ["ReentrantMaliciousReceiver"]: GetContractReturnType<ReentrantMaliciousReceiver$Type["abi"]>;
    ["contracts/test/ReentrantMaliciousReceiver.sol:IProposalRegistry"]: GetContractReturnType<IProposalRegistry$Type["abi"]>;
    ["contracts/test/ReentrantMaliciousReceiver.sol:ReentrantMaliciousReceiver"]: GetContractReturnType<ReentrantMaliciousReceiver$Type["abi"]>;
  }
}
